name: Build and Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build Go application
        working-directory: .github/workshow-service
        run: go build -o app main.go workshop.go

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: ./app

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t DOCKERHUB_USERNAME/aelm-workshop-23 .

      - name: Push Docker image
        run: docker push DOCKERHUB_USERNAME/aelm-workshop-23
